version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - run: mix deps.get

      - run: mix format --check-formatted
      - run: mix test

      - run:
          environment:
            MIX_ENV: docs
          command: mix inch report
